# Generated by Django 4.1.3 on 2022-11-24 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gymbros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('Mon', models.CharField(max_length=10)),
                ('Tues', models.CharField(max_length=10)),
                ('Wed', models.CharField(max_length=10)),
                ('Thu', models.CharField(max_length=10)),
                ('Fri', models.CharField(max_length=10)),
                ('Sat', models.CharField(max_length=10)),
                ('Sun', models.CharField(max_length=10)),
                ('Punch_in', models.CharField(max_length=50)),
                ('Punch_out', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20, unique=True)),
                ('inuse', models.IntegerField()),
                ('out', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('nb', models.IntegerField()),
                ('jobtitle', models.CharField(max_length=30)),
                ('legal', models.BooleanField()),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=160)),
                ('bill', models.IntegerField()),
                ('Punch_in', models.CharField(max_length=50)),
                ('Punch_out', models.CharField(max_length=50)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbros.customer')),
            ],
        ),
    ]
